<a href="https://colab.research.google.com/github/alistechworld/Machine-Learning-Hands-On-Practice-and-Code/blob/main/Day_12_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Encoding Categorical Data

In [2]:
from google.colab import files
uploaded = files.upload()

Saving customer (1).csv to customer (1).csv


In [4]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('customer (1).csv')

In [7]:
df.sample(5)

age  gender review education purchased
16   59    Male   Poor        UG       Yes
3    72  Female   Good        PG        No
10   98  Female   Good        UG       Yes
43   27    Male   Poor        PG        No
46   64  Female   Poor        PG        No

In [8]:
df = df.iloc[:, 2:]

In [9]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size = 0.2, )

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
X_train

review education
11     Good        UG
9      Good        UG
21  Average        PG
49     Good        UG
20  Average    School
14     Poor        PG
23     Good    School
45     Poor        PG
37  Average        PG
0   Average    School
35     Poor    School
12     Poor    School
40     Good    School
31     Poor    School
41     Good        PG
44  Average        UG
1      Poor        UG
17     Poor        UG
16     Poor        UG
27     Poor        PG
8   Average        UG
15     Poor        UG
28     Poor    School
10     Good        UG
29  Average        UG
6      Good    School
5   Average    School
34  Average    School
38     Good    School
43     Poor        PG
32  Average        UG
47     Good        PG
7      Poor    School
39     Poor        PG
33     Good        PG
42     Good        PG
26     Poor        PG
18     Good    School
46     Poor        PG
2      Good        PG

In [13]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [14]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [15]:
X_train = oe.transform(X_train)

In [16]:
X_train

array([[2., 1.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.]])

In [17]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
X_train

array([[2., 1.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.]])

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()

In [21]:
le.fit(y_train)

LabelEncoder()

In [22]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [23]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [24]:
y_train

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0])